# Generated by Django 4.1 on 2024-02-22 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=20, unique=True)),
                ('sex', models.CharField(choices=[('M', 'Мужской'), ('W', 'Женский')], default='W', max_length=1)),
                ('nickname', models.CharField(max_length=50)),
                ('date_arrival', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Животное',
                'verbose_name_plural': 'Животные',
                'ordering': ['date_arrival', 'nickname'],
            },
        ),
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.CreateModel(
            name='Weighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weighting_date', models.DateField(auto_now_add=True)),
                ('weight_kg', models.FloatField(verbose_name='Вес')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals_app.animal')),
            ],
            options={
                'verbose_name': 'Взвешивание',
                'verbose_name_plural': 'Взвешивания',
                'ordering': ['-weighting_date'],
            },
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals_app.animaltype')),
            ],
            options={
                'verbose_name': 'Порода',
                'verbose_name_plural': 'Породы',
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='breed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals_app.breed'),
        ),
        migrations.AddField(
            model_name='animal',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals_app.animal'),
        ),
        migrations.AddIndex(
            model_name='weighting',
            index=models.Index(fields=['animal', 'weighting_date'], name='animals_app_animal__2c8121_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['date_arrival', 'nickname'], name='animals_app_date_ar_b898ae_idx'),
        ),
    ]
