# Generated by Django 5.0.2 on 2024-02-21 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('animaltype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='animals_app.animaltype')),
                ('animal_breed', models.CharField(max_length=100)),
            ],
            bases=('animals_app.animaltype',),
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('breed_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='animals_app.breed')),
                ('inventory_number', models.CharField(max_length=20, unique=True)),
                ('sex', models.CharField(choices=[('M', 'Мужской'), ('W', 'Женский')], default='W', max_length=1)),
                ('nickname', models.CharField(max_length=50)),
                ('date_arrival', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animals_app.animal')),
            ],
            options={
                'ordering': ['date_arrival', 'nickname'],
            },
            bases=('animals_app.breed',),
        ),
        migrations.CreateModel(
            name='Weighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weighting_date', models.DateField(auto_now_add=True, unique=True)),
                ('weight_kg', models.FloatField(verbose_name='Вес')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals_app.animal')),
            ],
            options={
                'ordering': ['-weighting_date'],
                'indexes': [models.Index(fields=['weight_kg'], name='animals_app_weight__3debb5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['date_arrival', 'nickname'], name='animals_app_date_ar_b898ae_idx'),
        ),
    ]
