# Generated by Django 5.0.2 on 2024-02-21 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals_app.animaltype')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=20, unique=True)),
                ('sex', models.CharField(choices=[('M', 'Мужской'), ('W', 'Женский')], default='W', max_length=1)),
                ('nickname', models.CharField(max_length=50)),
                ('date_arrival', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals_app.animal')),
                ('breed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals_app.breed')),
            ],
            options={
                'ordering': ['date_arrival', 'nickname'],
            },
        ),
        migrations.CreateModel(
            name='Weighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weighting_date', models.DateField(auto_now_add=True, unique=True)),
                ('weight_kg', models.FloatField(verbose_name='Вес')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals_app.animal')),
            ],
            options={
                'ordering': ['-weighting_date'],
            },
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['date_arrival', 'nickname'], name='animals_app_date_ar_b898ae_idx'),
        ),
        migrations.AddIndex(
            model_name='weighting',
            index=models.Index(fields=['weight_kg'], name='animals_app_weight__3debb5_idx'),
        ),
        migrations.AddConstraint(
            model_name='weighting',
            constraint=models.UniqueConstraint(fields=('weighting_date', 'animal'), name='unique_weighting_per_animal_per_day'),
        ),
    ]
