# Generated by Django 4.1 on 2024-02-22 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weighting',
            unique_together={('weighting_date', 'animal')},
        ),
    ]
