# Generated by Django 4.1 on 2024-02-23 02:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('animals_app', '0002_alter_weighting_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighting',
            name='weighting_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
